version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:

#
#    "spring.flyway.user": "$MYSQLDB_USER",
#    "spring.flyway.password": "$MYSQLDB_ROOT_PASSWORD",
#    "spring.flyway.placeholders.keyABC": "valueXYZ",
#    "spring.flyway.url": "jdbc:mysql://localhost:3306/AdmAzsShippingDB?createDatabaseIfNotExist=true&serverTimezone=UTC",
#    "spring.flyway.driver-class-name": "com.mysql.cj.jdbc.Driver"